KhootClone/KhootClone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('quiz.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

KhootClone/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='chat_home'),
    path('notification', views.notification, name='chat_notification'),
]

KhootClone/quiz/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from quiz.views import *
from quiz.classview import *

urlpatterns = [
    path('', home, name='quiz-home'),
    #path('users/', users, name='quiz-users'),
    path('users/', UserView.as_view(), name='quiz-users'),
    path('users2/', UserTemplateView.as_view(), name='quiz-users-2'),
    path('users3/', UserListView.as_view(), name='quiz-users-3'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='quiz-user-detail'),
    #path('username/<slug:slug>/', UserDetailView.as_view(), name='quiz-user-slug'),
    path('create/', create),
    path('json/', json),
    path('pdf/', pdf),
    path('bg/', bg),
    path('blurbg/', blurbg),

    path('question/create/', QuestionCreateView.as_view(), name='quiz-question-create'),

    path('choice/create/', ChoiceCreateView.as_view(), name='quiz-choice-create'),
    path('choice/update/<int:pk>/', ChoiceUpdateView.as_view(), name='quiz-choice-update'),
    path('choice/delete/<int:pk>/', ChoiceDeleteView.as_view(), name='quiz-choice-delete'),

    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='quiz-user-delete'),

    path('member/list',             MemberListView.as_view(),   name='quiz_member_list'),
    path('member/create/',          MemberCreateView.as_view(), name='quiz_member_create'),
    path('member/read/<int:pk>/',   MemberDetailView.as_view(), name='quiz_member_read'),
    path('member/update/<int:pk>/', MemberUpdateView.as_view(), name='quiz_member_update'),
    path('member/delete/<int:pk>/', MemberDeleteView.as_view(), name='quiz_member_delete'),

    path('quiz/login/', QuizLogin.as_view(), name='quiz_login'),
    path('quiz/logout/', LogoutView.as_view(next_page='quiz-home'), name='quiz_logout'),
]

KhootClone/chat/models.py
from django.db import models

# Create your models here.

KhootClone/quiz/models.py
from django.db import models
from django.contrib.auth.models import User
import requests

# Create your models here.
class TimeStampedModel(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

class Member(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    quote = models.TextField()
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    picture_url = models.CharField(max_length=500, default='')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta:
        verbose_name_plural = 'สมาชิก'
        verbose_name = 'สมาชิก'

class Question(TimeStampedModel):
    # id  primary key
    member = models.ForeignKey(Member, null=True, on_delete=models.CASCADE)
    text = models.TextField(default='', verbose_name='คำถาม')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'คำถาม'
        verbose_name = 'คำถาม'


class Choice(TimeStampedModel):
    # id  primary key
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField(default='', verbose_name='คำตอบ')
    correct = models.BooleanField(default=False)

    def __str__(self):
        x = '/' if self.correct else 'x'
        return f'{x} {self.text}'

    class Meta:
        verbose_name_plural = 'ตัวเลือก'
        verbose_name = 'ตัวเลือก'

class Answer(TimeStampedModel):
    # id  primary key
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.member} {self.question} {self.choice}'

    class Meta:
        verbose_name_plural = 'คำตอบ'
        verbose_name = 'คำตอบ'

KhootClone/quiz/forms.py
from django import forms
from quiz.models import *

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'

KhootClone/chat/views.py
from django.shortcuts import render

# Create your views here.
def home(req):
    return render(req, 'chat/home.html')

def notification(req):
    return render(req, 'chat/notification.html')

KhootClone/quiz/views.py
import io

from django.shortcuts import render
from django.http import *
from reportlab.pdfgen import canvas
from PIL import Image, ImageFilter, ImageDraw
from django.contrib.auth.models import User

from quiz.forms import QuestionForm
from quiz.models import *

# Create your views here.
def home(req):
    #return HttpResponse('This is quiz home.')
    return render(req, 'quiz/home.html')

def users(req):
    #if req.method == 'GET':
    context = {
        'questions': Question.objects.count(),
        'user_count': User.objects.count(),
        'object_list': User.objects.all(),
    }
    return render(req, 'quiz/users.html', context)

def create(req):
    if req.method == 'POST':
        form = QuestionForm(req.POST)
        if form.is_valid():
            form.save()
    return HttpResponse('creating a quiz...')

def json(req):
    return JsonResponse({
        'name': 'Jack Daniel',
        'age': 25,
        'gpa': 3.99
    })

def pdf(req):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    p.drawString(100, 100, 'Django is Monolith')
    p.showPage()
    p.save()
    buffer.seek(0)
    # how to return a pdf with django
    return FileResponse(buffer, as_attachment=True,
                        filename='Yoyoyo.pdf')

def bg(req):
    f = open('italy.jpg', 'rb')
    return FileResponse(f)

def pil(req):
    img = Image.new('RGB', (100,50))
    drawer = ImageDraw.Draw(img)
    drawer.text((10,10), '1145005 Web Dev', fill=(100,250,120))  
    del drawer
    response = HttpResponse(content_type="image/png")  
    img.save(response, 'PNG')  
    return response

def blurbg(req):
    factor = 10
    if req.GET.get('factor'):
        factor = int(req.GET.get('factor'))
    img = Image.open('italy.jpg')
    blurimg = img.filter(ImageFilter.GaussianBlur(factor))
    res = HttpResponse(content_type='image/png')
    blurimg.save(res, 'PNG')
    return res

KhootClone/chat/templates/chat/home.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8"></meta>
    <title>Quiz Chat</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&display=swap"
          rel="stylesheet">
    <style>
        * {
            font-family: "Alegreya", serif;
            font-optical-sizing: auto;
            font-style: normal;
        }
    </style>
</head>
<body class="flex flex-col min-h-screen bg-zinc-700 text-zinc-100">
<div class="min-h-screen w-[600px] flex mx-auto flex-col">
    <div class="flex flex-col w-full">
        <span class="w-full text-left my-4">(A) <span class="bg-zinc-800 border rounded-xl py-2 px-6">question one?</span></span>
        <span class="w-full text-right"><span class="border rounded-xl py-2 px-6">answer one.</span> (B)</span>
        <span class="w-full text-left my-4">(A) <span class="bg-zinc-800 border rounded-xl py-2 px-6">question two?</span></span>
        <span class="w-full text-right"><span class="border rounded-xl py-2 px-6">answer two.</span> (B)</span>
    </div>
    <div class="fixed left-0 bottom-0 text-base px-3 md:px-4 m-auto w-full md:px-5 lg:px-1 xl:px-5">
        <div class="mx-auto flex flex-1 gap-4 text-base md:gap-5 lg:gap-6 md:max-w-3xl">
            <form id="form" class="w-full" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r1:"
                  data-state="closed">
                <div class="relative flex h-full max-w-full flex-1 flex-col">
                    <div class="group relative flex w-full items-center">
                        <div class="flex w-full flex-col gap-1.5 rounded-[26px] p-1.5 transition-colors bg-[#f4f4f4] dark:bg-token-main-surface-secondary">
                            <div class="flex items-end gap-1.5 md:gap-2">
                                <div class="flex min-w-0 flex-1 flex-col pl-4">
                                    <input type="text" name="message"
                                              tabindex="0"
                                              data-id="request-WEB:428b472a-a27a-4e1d-abd6-cfca53bfb29b-0"
                                              dir="auto" rows="1"
                                              placeholder="Message"
                                              class="m-0 resize-none border-0 rounded-[24px] bg-white px-10 py-2 text-zinc-800 focus:ring-0 focus-visible:ring-0 max-h-[25dvh] max-h-52"
                                              style="height: 40px; overflow-y: hidden;"/>
                                </div>
                                <button type="submit" aria-label="Send prompt" data-testid="send-button"
                                        class="mb-1 me-1 flex h-8 w-8 items-center justify-center rounded-full bg-black text-white transition-colors hover:opacity-70 focus-visible:outline-none focus-visible:outline-black disabled:text-[#f4f4f4] disabled:hover:opacity-100 dark:bg-white dark:text-black dark:focus-visible:outline-white disabled:dark:bg-token-text-quaternary dark:disabled:text-token-main-surface-secondary disabled:bg-[#D7D7D7]"
                                        >
                                    <svg width="32" height="32" viewBox="0 0 32 32" fill="none"
                                         xmlns="http://www.w3.org/2000/svg" class="icon-2xl">
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M15.1918 8.90615C15.6381 8.45983 16.3618 8.45983 16.8081 8.90615L21.9509 14.049C22.3972 14.4953 22.3972 15.2189 21.9509 15.6652C21.5046 16.1116 20.781 16.1116 20.3347 15.6652L17.1428 12.4734V22.2857C17.1428 22.9169 16.6311 23.4286 15.9999 23.4286C15.3688 23.4286 14.8571 22.9169 14.8571 22.2857V12.4734L11.6652 15.6652C11.2189 16.1116 10.4953 16.1116 10.049 15.6652C9.60265 15.2189 9.60265 14.4953 10.049 14.049L15.1918 8.90615Z"
                                              fill="currentColor"></path>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    let url = `ws://${window.location.host}/ws/chat/`
    const socket = new WebSocket(url)
    socket.onmessage = function(e) {
        let data = JSON.parse(e.data)
        console.log('onmessage()', data)
    }

    let form = document.getElementById('form')
    form.addEventListener('submit', (e) => {
        e.preventDefault()
        let message = e.target.message.value
        socket.send(JSON.stringify({
            'message': message
        }))
        form.reset()
    })
</script>
</body>
</html>

KhootClone/chat/templates/chat/notification.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8"></meta>
    <title>Quiz Chat</title>
    <script src="https://unpkg.com/htmx.org@2.0.2" integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&display=swap"
          rel="stylesheet">
    <script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>
    <style>
        * {
            font-family: "Alegreya", serif;
            font-optical-sizing: auto;
            font-style: normal;
        }
    </style>
</head>
<body hx-ext="ws" ws-connect="/ws/user_online_notification/" class="flex flex-col min-h-screen bg-zinc-700 text-zinc-100">
<div class="min-h-screen w-[600px] flex mx-auto flex-col">
    <div class="flex flex-col w-full">
        <span class="w-full text-left my-4">(A) <span class="bg-zinc-800 border rounded-xl py-2 px-6">question one?</span></span>
        <span class="w-full text-right"><span class="border rounded-xl py-2 px-6">answer one.</span> (B)</span>
        <span class="w-full text-left my-4">(A) <span class="bg-zinc-800 border rounded-xl py-2 px-6">question two?</span></span>
        <span class="w-full text-right"><span class="border rounded-xl py-2 px-6">answer two.</span> (B)</span>
    </div>

</div>
</body>
</html>

KhootClone/quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="UTF-8"></meta>
    <title>Quiz Home</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
    <style>
* {
  font-family: "Alegreya", serif;
  font-optical-sizing: auto;
  font-style: normal;
}
    </style>
  </head>
  <body class="flex flex-col min-h-screen">
    {% include 'quiz/header.html' %}
    <main class="flex flex-col grow bg-white">
      {% block main %}

      {% endblock %}
    </main>
    {% include 'quiz/footer.html' %}
  </body>
</html>

KhootClone/quiz/templates/quiz/choice_confirm_delete.html
{% extends 'quiz/base.html' %}

{% block main %}

Confirm you are deleting {{ object }} ??

{% endblock %}

KhootClone/quiz/templates/quiz/choice_form.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-col mx-10 justify-around">
    <form action="{% url 'quiz-choice-create' %}" method="POST">
        <div class="shadow-xl mx-auto">{{ form.question }}</div>
        <div class="shadow-xl mx-auto">{{ form.text }}</div>
        <div class="shadow-xl mx-auto">{{ form.correct }}</div>
        <button class="px-6 py-1 my-2 hover:bg-green-800 mx-auto border rounded-xl" type="submit">Submit</button>
    </form>
</div>


{% endblock %}

KhootClone/quiz/templates/quiz/choice_update_form.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-col mx-10 justify-around">
    <form action="{% url 'quiz-choice-update' %}" method="POST">
        <div class="shadow-xl mx-auto">{{ form.question }}</div>
        <div class="shadow-xl mx-auto">{{ form.text }}</div>
        <div class="shadow-xl mx-auto">{{ form.correct }}</div>
        <button class="px-6 py-1 my-2 hover:bg-green-800 mx-auto border rounded-xl" type="submit">Submit</button>
    </form>
</div>


{% endblock %}

KhootClone/quiz/templates/quiz/components/user.html
<figure class="md:flex bg-slate-100 max-w-96 rounded-xl m-8 p-8 shadow-md">
  <img class="w-24 h-24 rounded-full mx-auto" src="{{ user.member.picture_url }}" alt="" width="384" height="512">
  <div class="pt-6 text-center space-y-4">
    <blockquote>
      <p class="text-lg font-medium">
      “{{ user.member.quote }}”
      </p>
    </blockquote>
    <div class="h-10 text-sky-500 flex-grow">
      <span>
        {{ user.first_name }} {{ user.last_name }}
      </span>
    </div>
    <figcaption class="font-medium grow">
      <div class="text-green-700">
        <span class="text-xs">{{ user.member.state }}</span>,
        <span class="font-bold">{{ user.member.country }}</span>
      </div>
    </figcaption>
    <div class="w-full text-green-700 flex justify-around ">
      <a href="{% url 'quiz_member_update' pk=user.id %}"
         class="py-2 w-12 flex text-blue-500 justify-around rounded-xl hover:text-white hover:bg-blue-400 hover:shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-pen"><path d="M11.5 15H7a4 4 0 0 0-4 4v2"/><path d="M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"/><circle cx="10" cy="7" r="4"/></svg>
      </a>
      <a href="{% url 'quiz-user-delete' pk=user.id %}"
         class="py-2 w-12 flex text-red-500 justify-around rounded-xl hover:text-white hover:bg-red-400 hover:shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-x"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="17" x2="22" y1="8" y2="13"/><line x1="22" x2="17" y1="8" y2="13"/></svg>
      </a>
    </div>
  </div>
</figure>

KhootClone/quiz/templates/quiz/footer.html
<footer class="w-full flex-col bg-green-700 text-center text-xs py-4">
  <div class="flex justify-around border-b py-4 text-zinc-400">
    <div>
      <h1>Top Players</h1>
      <ul>
        <li>Lisa🥰🥰</li>
        <li>Damian😠</li>
        <li>Mayan321</li>
        <li>Jackie98</li>
      </ul>
    </div>
    <div>
      <h1 class="text-zinc-200 text-lg font-bold">Social Networks</h1>
      <ul class="list disc-none">
        <li class="hover:text-red-400"><svg class="inline" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube"><path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17"/><path d="m10 15 5-3-5-3z"/></svg>
          @uQuizyt</li>
        <li class="hover:text-blue-400"><svg class="inline" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>@uQuizfb</li>
        <li class="hover:text-sky-300"><svg class="inline" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitter"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/></svg>@uQuizx</li>
      </ul>
    </div>
    <div>
      <h1 class="pb-2 text-zinc-200 text-lg font-bold shadow-sm">Address</h1>
      <ul class="list disc-none">
        <li class="pb-1">85 Satholamark Rd.</li>
        <li class="pb-1">Warin Chamrab</li>
        <li class="pb-1">Ubon Ratchathani</li>
        <li class="pb-1"><span class="font-bold text-white">Thailand</span>, 34190</li>
        <li class="pb-1"><a href="tel:+66045353400" class="font-bold font-bold text-zinc-200 hover:text-white">+66 045 353 400</a></li>
      </ul>
    </div>
  </div>
  <div class="w-full pt-4 text-zinc-200">
    Copyleft © uQuiz All Seats Reserved.
  </div>
</footer>

KhootClone/quiz/templates/quiz/home.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8"></meta>
        <title>Quiz Home</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="flex flex-col min-h-screen">
      {% include 'quiz/header.html' %}
      <main class="flex flex-col grow bg-white">
        <h1 class="text-center">QUIZ HOME</h1>
      </main>
      <footer class="w-full h-10 bg-green-700 text-white text-center text-xs py-4">
        Copyleft © uQuiz All Seats Reserved.
      </footer>
    </body>
</html>

KhootClone/quiz/templates/quiz/member/delete.html
{% extends 'quiz/base.html' %}

{% block main %}

Deleting user - {{ object.username }} - {{ object.first_name }} {{ object.last_name }} ??
<form method="POST">
{% csrf_token %}
  <button type="submit">Confirm</button>
</form>

{% endblock %}

KhootClone/quiz/templates/quiz/member/update.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-col mx-10 justify-around">
  <img class="z-10 w-36 h-36 mx-auto mt-10 shadow-xl rounded-full"
  src="{{ form.instance.picture_url }}" alt="profile"/>
  <div class="w-[640px] mx-auto shadow-xl rounded-xl mt-[-32px] mb-10 p-10 bg-zinc-100">
    <form method="POST">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          User
        </label>
        <select id="id_user" name="user" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 "> 
          {% for w in form.user.subwidgets %}
            {% if w.data.selected %}
            <option selected="true" value="{{ w.data.value }}">{{ w.data.label }}</option>
            {% else %}
              {{ w }}
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          Quote
        </label>
        <textarea id="id_quote" rows="4" placeholder="quote" name="quote"
          class="block p-2.5 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500">{{ form.quote.value }}</textarea>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          State
        </label>
        <input id="id_state" type="text" placeholder="state" name="state" value="{{ form.state.value }}"
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          Country
        </label>
        <input id="id_country" type="text" placeholder="country" name="country" value="{{ form.country.value }}"
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="py-2"><button class="px-6 py-1 my-2 hover:bg-green-700 hover:text-white bg-green-100 mx-auto border rounded-xl" type="submit">Submit</button></div>
    </form>
  </div>
</div>


{% endblock %}

KhootClone/quiz/templates/quiz/member_update_form.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-col mx-10 justify-around">
  <img class="z-10 w-36 h-36 mx-auto mt-10 shadow-xl rounded-full"
  src="{{ form.instance.picture_url }}" alt="profile"/>
  <div class="w-[640px] mx-auto shadow-xl rounded-xl mt-[-32px] mb-10 p-10 bg-zinc-100">
    <form method="POST">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          User
        </label>
        <select id="id_user" name="user" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 "> 
          {% for w in form.user.subwidgets %}
            {% if w.data.selected %}
            <option selected="true" value="{{ w.data.value }}">{{ w.data.label }}</option>
            {% else %}
              {{ w }}
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          Quote
        </label>
        <textarea id="id_quote" rows="4" placeholder="quote" name="quote"
          class="block p-2.5 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500">{{ form.quote.value }}</textarea>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          State
        </label>
        <input id="id_state" type="text" placeholder="state" name="state" value="{{ form.state.value }}"
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          Country
        </label>
        <input id="id_country" type="text" placeholder="country" name="country" value="{{ form.country.value }}"
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="py-2"><button class="px-6 py-1 my-2 hover:bg-green-700 hover:text-white bg-green-100 mx-auto border rounded-xl" type="submit">Submit</button></div>
    </form>
  </div>
</div>


{% endblock %}

KhootClone/quiz/templates/quiz/question_form.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-wrap mx-10 justify-around">
    {{ form }}
</div>


{% endblock %}

KhootClone/quiz/templates/quiz/user.html
{% extends 'quiz/base.html' %}

{% block main %}

<div class="flex flex-wrap mx-10 justify-around">
    {% include 'quiz/components/user.html' with user=object %}
</div>


{% endblock %}